### ISSUE TITLE
Cannot find ios project file to run

### ISSUE THREAD

**Issue by mak2014** [TomClarkson/hanzi-gold#5]
First of all, thanks a lot for the app source code. Can you please advise why the ios folder is missing. I am trying to run in iOS simulator. Please advise.

**Comment by TomClarkson** [comment]
Thanks :) The ios folder is missing because this app was built to run in exponent https://exponentjs.com/

To run in the simulator download exponent, run the exponent app, click open project and then there are buttons to install the project on the simulator and run on the simulator

Related to #4

**Comment by TomClarkson** [comment]
I've updated the readme

**Comment by mak2014** [comment]
Thanks Tom. Much appreciated.
